account/urls.py
from django.urls import path
from account.views import *

app_name = "account"

urlpatterns = [
    path("user-register/", RegisterView.as_view(), name="user-register"),
    path("user-login/", LoginView.as_view(), name="user-login"),
    path("user-logout/", LogoutView.as_view(), name="user-logout"),
    path("user-delete/", DeleteView.as_view(), name="user-delete"),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todo/", include("todo.urls")),
    path("student/", include("student.urls")),
    path("account/", include("account.urls")),
    # path("", index),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                   document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from student.views import student_view, courses_view
from student.class_views import *

app_name = "student"

urlpatterns = [
    # path("all_students/", student_view, name="student_list"),
    path("courses/", courses_view),
    path("all_students/", AllStudentsView.as_view(), name="student_list_new"),
    path("add-course/", AddCourseView.as_view(), name="add_course"),
    path("add-profile/", AddProfileView.as_view(), name="add_profile"),
    path("all-teachers/", AllTeachersView.as_view(), name="teachers")

]

todo/urls.py
from django.urls import path
from todo.views import *

app_name = "todo"

urlpatterns = [
    path("home/", task_view, name="home"),
    path("task_student/<int:st_id>/", task_student),
]

account/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    fullname = models.CharField(max_length=64)
    score = models.PositiveIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)


class Teacher(models.Model):
    fullname = models.CharField(max_length=64)
    score = models.PositiveIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

class Course(models.Model):
    title = models.CharField(max_length=64)
    code = models.PositiveIntegerField()
    desc = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    students = models.ManyToManyField(Student, related_name="courses")


class Profile(models.Model):
    bio = models.TextField()
    avatar = models.ImageField(upload_to="images/%Y/%m/", null=True)
    student = models.OneToOneField(Student, related_name="profile", on_delete=models.CASCADE, blank=True, null=True)
    teacher = models.OneToOneField(Teacher, related_name="profile", on_delete=models.CASCADE, blank=True, null=True)
    phone_number = models.CharField(max_length=13)
    img = models.ImageField(upload_to="images/%Y/%m/", null=True, blank=True)
    file = models.FileField(upload_to="files/%Y/%m/", null=True, blank=True)

    def __str__(self):
        return self.bio

todo/models.py
from django.db import models
from student.models import Student


class Task(models.Model):
    title = models.CharField(max_length=256)
    done = models.BooleanField(default=False)
    category = models.CharField(max_length=64)
    description = models.TextField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="tasks")

    def __str__(self):
        return self.title


class TypeCategory(models.Model):
    title = models.CharField(max_length=32)
    tasks = models.ManyToManyField(Task)

    def __str__(self):
        return self.title

account/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class UserRegisterForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "username", "password"]


class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]

student/forms.py
from django.forms import ModelForm, Form, CharField, ImageField, ModelMultipleChoiceField
from student.models import Student, Course, Profile


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["fullname"]


class CourseForm(ModelForm):
    class Meta:
        model = Course
        exclude = ["students", ]


# class ProfileForm(ModelForm):
#     class Meta:
#         model = Profile
#         fields = ["bio", "avatar", "student"]


class ProfileForm(Form):
    bio = CharField()
    avatar = ImageField()
    student = ModelMultipleChoiceField(queryset=Student.objects.all())

account/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from account.forms import *
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.forms import AuthenticationForm


class RegisterView(View):
    form = UserRegisterForm()
    template = "account/register.html"

    def get(self, request):
        return render(request, self.template, {"form": self.form})

    def post(self, request):
        st_form = UserRegisterForm(request.POST)
        if st_form.is_valid():
            new_user = User.objects.create_user(
                username=request.POST["username"],
                email="",
                password=request.POST["password"]
            )
            if new_user:
                return redirect("todo:home")
        return render(request, self.template,
                      {"form": self.form, "message": "یوزرنیم یا پسورد اشتباه یا تکراری است"}
                      )


class LoginView(View):
    form = UserLoginForm()
    template = "account/login.html"

    def get(self, request):
        return render(request, self.template, {"form": self.form})

    def post(self, request):
        form_data = UserLoginForm(request.POST)

        # if form_data.is_valid():
        user = authenticate(username=request.POST["username"],
                            password=request.POST["password"])

        if user and user.is_authenticated:
            login(request, user)
            return redirect("student:add_course")
        return render(request, self.template, {"form": self.form, "message": "یوزر یا پسورد اشتباه است"})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        return redirect("account:user-login")

class DeleteView(View):
    def get(self, request):
        if request.user.is_authenticated:
            try:
                user = User.objects.get(id=request.user.id)
                user.delete()
                return redirect("todo:home")
            except:
                return redirect("student:add_course")

myapp/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("helloooooo")

student/views.py
from django.shortcuts import render, redirect
from student.models import Student, Course
from student.forms import StudentForm


def student_view(request):
    form = StudentForm()
    html_file = "student/all_student.html"
    if request.method == "GET":
        all_students = Student.objects.all()
        context = {"students": all_students, "form": form}
        return render(request, html_file, context)
    elif request.method == "POST":
        d = StudentForm(request.POST)
        if d.is_valid():
            saved_obj = d.save()
        # data = request.POST
        # fullname1 = data["fullname"]
        # username1 = data["username"]
        # phone1 = data["phone_number"]
        # student_object = Student.objects.create(fullname=fullname1, username=username1, phone_number=phone1, score=0)
            if saved_obj:
                return redirect("todo:home")
        return render(request, html_file, {"form": form})


def courses_view(request):
    all_courses = Course.objects.all()
    context = {"courses": all_courses}
    return render(request, "student/courses.html", context)

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from todo.models import Task
from student.models import Student, Course
from django.views import View

def task_view(request):
    if request.method == "GET":
        tasks = list(Task.objects.all())
        context = {"list_tasks": tasks}
        return render(request, 'todo/start.html', context)


def task_student(request, st_id):

    tasks_student = Task.objects.filter(student_id=st_id)
    context = {"tasks": tasks_student}
    return render(request, "todo/list_student_1.html", context)

student/templates/student/add_course.html
{% extends "student_base.html" %}
{% block content %}
    <form action={% url "student:add_course" %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ثبت درس">
    </form>
        <a class="btn bg-primary text-light" href={% url "account:user-logout" %}>خروج</a>
        <a class="btn bg-danger text-light" href={% url "account:user-delete" %}>حذف حساب کاربری</a>

{% endblock %}

student/templates/student/add_profile.html
{% extends "student_base.html" %}
{% block content %}
    <form action={% url "student:add_profile" %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ثبت دانشجو">
    </form>
{% endblock %}

student/templates/student/all_student.html
{% extends "student_base.html" %}

{% block content %}
  <ul>
      {% for student in students%}
        {% if student.img %}
          <li>{{student.fullname}}: {{student.score}}</li>
          <img src={{student.img.url}}>
          {% for course in student.courses.all %}
            <p>{{course.title}}</p>
          {% endfor %} 
          {% for task in student.tasks.all %}
            <p>{{task.title}}</p>
          {% endfor %}
        {% endif %}
      {% endfor %}
    </ul>
    <p>{{message}}</p>
    <form action={% url "student:student_list_new" %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ثبت دانشجو">
    </form>
{% endblock %}

student/templates/student/courses.html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>Courses Page</h1>
    <ul>
      {% for course in courses%}
      <li>{{course.title}}: {{course.code}}</li>
      {% for student in course.students.all %}
      <p>{{student.fullname}}</p>
      {% endfor %} {% endfor %}
    </ul>
  </body>
</html>

student/templates/student/create_student.html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <form action="/student/all_students/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
  </body>
</html>

student/templates/student/teachers.html
{% extends "student_base.html" %}

{% block content %}
  <ul>
      {% for teacher in teachers%}
        <p>{{teacher.fullname}}</p>
      {% endfor %}
        
{% endblock %}

student/templates/student_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

    {% block title %}
    <title>Local Library</title>
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}

    <footer class="mt-auto bg-dark">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-3">
            <h5>About Us</h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac ante mollis quam tristique convallis.
            </p>
          </div>
          <div class="col-md-4 mb-3">
            <h5>Quick Links</h5>
            <ul class="list-unstyled">
              <li><a href="#" class="text-decoration-none text-white">Home</a></li>
              <li><a href="#" class="text-decoration-none text-white">Services</a></li>
              <li><a href="#" class="text-decoration-none text-white">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-4 mb-3">
            <h5>Follow Us</h5>
            <ul class="list-inline social-icons">
              <li class="list-inline-item">
                <a href="#" class="text-white"><i class="bi bi-twitter"></i></a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="text-white"><i class="bi bi-twitter"></i></a>
              </li>
              <li class="list-inline-item">
                <a href="#" class="text-white"><i class="bi bi-instagram"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <hr class="mb-4" />
        <div class="row">
          <div class="col-md-12 text-center">
            <p>&copy; 2023 Your Company. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/design-with-bootstrap.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
  </head>
  <body class="bg-dark">
    <div>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">My site</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">ویژگی ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">قیمت</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">خاموش</a>
              </li>
              <li class="nav-item">
                <div class="dropdown">
                  <button
                    class="btn btn-secondary dropdown-toggle"
                    type="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Dropdown
                  </button>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="http://127.0.0.1:8000/templates/new.html">about me</a>
                    </li>
                    <li><button class="dropdown-item" type="button">Another action</button></li>
                    <li><button class="dropdown-item" type="button">Something else here</button></li>
                  </ul>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <h1 class="text-primary">Hello, world!</h1>
    <div class="row">
      <div class="card col-6 p-5">
        <img src="C:\Users\Hp\Desktop\cat.jpeg" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the bulk of the card’s content.
          </p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>

      <div class="card col-6 p-5">
        <img src="C:\Users\Hp\Desktop\cat.jpeg" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the bulk of the card’s content.
          </p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/new.html
<html>
  <head>
    <title>My First Webpage</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <h1 class="id_class">Welcome to My Page</h1>
    <p class="id_class">This is <a href="http://127.0.0.1:8000/start.html">Visit Example</a> a paragraph.</p>
    <a href="https://example.com">Visit Example</a>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="48"
      height="48"
      fill="currentColor"
      class="bi bi-instagram"
      viewBox="0 0 16 16"
      color="#000000"
    >
      <path
        d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"
      />
    </svg>
  </body>
</html>

todo/templates/design-with-bootstrap.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
  </head>
  <body class="bg-dark">
    <div>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">My site</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/new.html">ویژگی ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">قیمت</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">خاموش</a>
              </li>
              <li class="nav-item">
                <div class="dropdown">
                  <button
                    class="btn btn-secondary dropdown-toggle"
                    type="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Dropdown
                  </button>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="http://127.0.0.1:8000/templates/new.html">about me</a>
                    </li>
                    <li><button class="dropdown-item" type="button">Another action</button></li>
                    <li><button class="dropdown-item" type="button">Something else here</button></li>
                  </ul>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <h1 class="text-primary">Hello, world!</h1>
    <div class="row">
      <div class="card col-6 p-5">
        <img src="C:\Users\Hp\Desktop\cat.jpeg" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the bulk of the card’s content.
          </p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>

      <div class="card col-6 p-5">
        <img src="C:\Users\Hp\Desktop\cat.jpeg" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the bulk of the card’s content.
          </p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

todo/templates/todo/list_student_1.html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    {% for task in tasks %}
    <p>{{task.title}}</p>
    {% endfor %}
  </body>
</html>

todo/templates/todo/new.html
<html>
  <head>
    <title>My First Webpage</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <h1 class="id_class"></h1>
    {% for name in student %} {% if name == "Ali" %}
    <p>{{name}}</p>
    {% endif %} {% endfor %}
    <p class="id_class">This is <a href="http://127.0.0.1:8000/start.html">Visit Example</a> a paragraph.</p>
    <a href="https://example.com">Visit Example</a>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="48"
      height="48"
      fill="currentColor"
      class="bi bi-instagram"
      viewBox="0 0 16 16"
      color="#000000"
    >
      <path
        d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"
      />
    </svg>
  </body>
</html>

todo/templates/todo/start.html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading23123123</h1>
    <p id="id_class">This is a paragraph.</p>
    {% for task_obj in list_tasks %}
    <p>{{task_obj.title}} | {{task_obj.student.fullname}}</p>
    {% endfor %}
    <!-- {% for text in tasks_titles %}
    <p>{{text}}</p>
    {% endfor %} -->
  </body>
</html>